---
-
 
  # Target: where our play will run and options it will run with
  hosts: WINSER1
  # Task: the list of tasks that will be executed within the playbook
  tasks:
   - name: Install only particular updates based on the KB numbers
     win_updates:
       category_name:
       - SecurityUpdates
       whitelist:
       - KB4507457 
       - KB4507448
...

